In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import nltk

In [2]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

#### Tokenization

In [2]:
paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [7]:
sentences = nltk.sent_tokenize(paragraph)

In [8]:
len(sentences)

31

In [9]:
sentences[0]

'I have three visions for India.'

In [10]:
word_3=nltk.word_tokenize(sentences[0])

In [11]:
word_3

['I', 'have', 'three', 'visions', 'for', 'India', '.']

In [12]:
word=nltk.word_tokenize(paragraph)

In [13]:
word

['I',
 'have',
 'three',
 'visions',
 'for',
 'India',
 '.',
 'In',
 '3000',
 'years',
 'of',
 'our',
 'history',
 ',',
 'people',
 'from',
 'all',
 'over',
 'the',
 'world',
 'have',
 'come',
 'and',
 'invaded',
 'us',
 ',',
 'captured',
 'our',
 'lands',
 ',',
 'conquered',
 'our',
 'minds',
 '.',
 'From',
 'Alexander',
 'onwards',
 ',',
 'the',
 'Greeks',
 ',',
 'the',
 'Turks',
 ',',
 'the',
 'Moguls',
 ',',
 'the',
 'Portuguese',
 ',',
 'the',
 'British',
 ',',
 'the',
 'French',
 ',',
 'the',
 'Dutch',
 ',',
 'all',
 'of',
 'them',
 'came',
 'and',
 'looted',
 'us',
 ',',
 'took',
 'over',
 'what',
 'was',
 'ours',
 '.',
 'Yet',
 'we',
 'have',
 'not',
 'done',
 'this',
 'to',
 'any',
 'other',
 'nation',
 '.',
 'We',
 'have',
 'not',
 'conquered',
 'anyone',
 '.',
 'We',
 'have',
 'not',
 'grabbed',
 'their',
 'land',
 ',',
 'their',
 'culture',
 ',',
 'their',
 'history',
 'and',
 'tried',
 'to',
 'enforce',
 'our',
 'way',
 'of',
 'life',
 'on',
 'them',
 '.',
 'Why',
 '?',
 '

#### Stemming, Stop words and Lammitization

In [14]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [15]:
del word

In [16]:
stemmer = PorterStemmer()

In [17]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [18]:
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i] =' '.join(words)

In [19]:
sentences

['I three vision india .',
 'In 3000 year histori , peopl world come invad us , captur land , conquer mind .',
 'from alexand onward , greek , turk , mogul , portugues , british , french , dutch , came loot us , took .',
 'yet done nation .',
 'We conquer anyon .',
 'We grab land , cultur , histori tri enforc way life .',
 'whi ?',
 'becaus respect freedom others.that first vision freedom .',
 'I believ india got first vision 1857 , start war independ .',
 'It freedom must protect nurtur build .',
 'If free , one respect us .',
 'My second vision india ’ develop .',
 'for fifti year develop nation .',
 'It time see develop nation .',
 'We among top 5 nation world term gdp .',
 'We 10 percent growth rate area .',
 'our poverti level fall .',
 'our achiev global recognis today .',
 'yet lack self-confid see develop nation , self-reli self-assur .',
 'isn ’ incorrect ?',
 'I third vision .',
 'india must stand world .',
 'becaus I believ unless india stand world , one respect us .',
 'onl

In [20]:
from nltk.stem import WordNetLemmatizer

In [21]:
lematizer=WordNetLemmatizer()

In [22]:
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [lematizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i] =' '.join(words)

In [23]:
sentences

['I three vision india .',
 'In 3000 year histori , peopl world come invad u , captur land , conquer mind .',
 'alexand onward , greek , turk , mogul , portugues , british , french , dutch , came loot u , took .',
 'yet done nation .',
 'We conquer anyon .',
 'We grab land , cultur , histori tri enforc way life .',
 'whi ?',
 'becaus respect freedom others.that first vision freedom .',
 'I believ india got first vision 1857 , start war independ .',
 'It freedom must protect nurtur build .',
 'If free , one respect u .',
 'My second vision india ’ develop .',
 'fifti year develop nation .',
 'It time see develop nation .',
 'We among top 5 nation world term gdp .',
 'We 10 percent growth rate area .',
 'poverti level fall .',
 'achiev global recognis today .',
 'yet lack self-confid see develop nation , self-reli self-assur .',
 '’ incorrect ?',
 'I third vision .',
 'india must stand world .',
 'becaus I believ unless india stand world , one respect u .',
 'onli strength respect streng

#### Bag of Word Technique 

In [24]:
paragraph_repeat = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [25]:
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [26]:
ps=PorterStemmer()
lemmatizerr=WordNetLemmatizer()

In [27]:
sentences=nltk.sent_tokenize(paragraph_repeat)

In [28]:
corpus=[]

In [29]:
for i in range (len(sentences)):
    removal=re.sub('[^a-zA-Z]',' ',sentences[i])
    removal=removal.lower()
    removal=removal.split()
    removal=[lemmatizerr.lemmatize(word)for word in removal if not word in set(stopwords.words('english'))]
    removal=' '.join(removal)
    corpus.append(removal)

In [30]:
corpus

['three vision india',
 'year history people world come invaded u captured land conquered mind',
 'alexander onwards greek turk mogul portuguese british french dutch came looted u took',
 'yet done nation',
 'conquered anyone',
 'grabbed land culture history tried enforce way life',
 '',
 'respect freedom others first vision freedom',
 'believe india got first vision started war independence',
 'freedom must protect nurture build',
 'free one respect u',
 'second vision india development',
 'fifty year developing nation',
 'time see developed nation',
 'among top nation world term gdp',
 'percent growth rate area',
 'poverty level falling',
 'achievement globally recognised today',
 'yet lack self confidence see developed nation self reliant self assured',
 'incorrect',
 'third vision',
 'india must stand world',
 'believe unless india stand world one respect u',
 'strength respect strength',
 'must strong military power also economic power',
 'must go hand hand',
 'good fortune worked

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
c_v=CountVectorizer(max_features=1500)
vector=c_v.fit_transform(corpus).toarray()

In [32]:
df = pd.DataFrame(data=vector)

In [33]:
df

0    1    2    3    4    5    6    7    8    9    ...  104  105  106  107  \
0     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    1   
1     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2     0    1    0    0    0    0    0    0    0    1  ...    1    0    0    0   
3     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4     0    0    0    0    1    0    0    0    0    0  ...    0    0    0    0   
5     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
6     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
7     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    1   
8     0    0    0    0    0    0    0    1    0    0  ...    0    0    0    1   
9     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
10    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
11    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    1   
12    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
13    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
14    0    0    0    1    0    0    0    0    0    0  ...    0    0    0    0   
15    0    0    0    0    0    1    0    0    0    0  ...    0    0    0    0   
16    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
17    1    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
18    0    0    0    0    0    0    1    0    0    0  ...    0    0    0    0   
19    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
20    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    1   
21    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
22    0    0    0    0    0    0    0    1    0    0  ...    0    1    0    0   
23    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
24    0    0    1    0    0    0    0    0    0    0  ...    0    0    0    0   
25    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
26    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
27    0    0    0    0    0    0    0    0    0    0  ...    0    0    1    0   
28    0    0    0    0    0    0    0    0    1    0  ...    0    0    0    0   
29    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
30    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

    108  109  110  111  112  113  
0     0    0    0    0    0    0  
1     0    0    0    1    1    0  
2     0    0    0    0    0    0  
3     0    0    0    0    0    1  
4     0    0    0    0    0    0  
5     0    1    0    0    0    0  
6     0    0    0    0    0    0  
7     0    0    0    0    0    0  
8     1    0    0    0    0    0  
9     0    0    0    0    0    0  
10    0    0    0    0    0    0  
11    0    0    0    0    0    0  
12    0    0    0    0    1    0  
13    0    0    0    0    0    0  
14    0    0    0    1    0    0  
15    0    0    0    0    0    0  
16    0    0    0    0    0    0  
17    0    0    0    0    0    0  
18    0    0    0    0    0    1  
19    0    0    0    0    0    0  
20    0    0    0    0    0    0  
21    0    0    0    1    0    0  
22    0    0    0    1    0    0  
23    0    0    0    0    0    0  
24    0    0    0    0    0    0  
25    0    0    0    0    0    0  
26    0    0    1    0    0    0  
27    0    0    0    0    0    0  
28    0    0    0    0    0    0  
29    0    0    1    0    0    0  
30    0    0    0    0    0    0  

[31 rows x 114 columns]

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf=TfidfVectorizer(max_features=1500)
tfidf_vector=tf_idf.fit_transform(corpus).toarray()

In [37]:
tfidf_vector

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.25883507, 0.30512561,
        0.        ],
       [0.        , 0.28867513, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [38]:
df_2 = pd.DataFrame(data=tfidf_vector)

In [39]:
df_2

0         1         2        3         4    5         6         7    \
0   0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
1   0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
2   0.0  0.288675  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
3   0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
4   0.0  0.000000  0.000000  0.00000  0.746061  0.0  0.000000  0.000000   
5   0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
6   0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
7   0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
8   0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.347468   
9   0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
10  0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
11  0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
12  0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
13  0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
14  0.0  0.000000  0.000000  0.44387  0.000000  0.0  0.000000  0.000000   
15  0.0  0.000000  0.000000  0.00000  0.000000  0.5  0.000000  0.000000   
16  0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
17  0.5  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
18  0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.251881  0.000000   
19  0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
20  0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
21  0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
22  0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.397615   
23  0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
24  0.0  0.000000  0.341529  0.00000  0.000000  0.0  0.000000  0.000000   
25  0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
26  0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
27  0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
28  0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
29  0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   
30  0.0  0.000000  0.000000  0.00000  0.000000  0.0  0.000000  0.000000   

         8         9    ...       104       105       106       107       108  \
0   0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.548305  0.000000   
1   0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
2   0.000000  0.288675  ...  0.288675  0.000000  0.000000  0.000000  0.000000   
3   0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
4   0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
5   0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
6   0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
7   0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.287960  0.000000   
8   0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.275939  0.389309   
9   0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
10  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
11  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.408896  0.000000   
12  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
13  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
14  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
15  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
16  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
17  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
18  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000

### SMS SPAM COLLECTION DATASET

In [44]:
messages_df=pd.read_csv('Spam dataset\\SMSSpamCollection',sep='\t',names=['labels','messages'])

In [45]:
messages_df

labels                                           messages
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [46]:
messages_df['labels'].value_counts()

ham     4825
spam     747
Name: labels, dtype: int64

In [47]:
messages_df['messages']

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: messages, Length: 5572, dtype: object

In [49]:
len(messages_df)

5572

In [53]:
corpus_2=[]

In [92]:
corpus_3=[]

In [54]:
for i in range (0, len(messages_df)):
    removal=re.sub('[^a-zA-Z]',' ',messages_df['messages'][i])
    removal=removal.lower()
    removal=nltk.word_tokenize(removal)
    removal=[ps.stem(word)for word in removal if not word in set(stopwords.words('english'))]
    removal=' '.join(removal)
    corpus_2.append(removal)

In [93]:
for i in range (0, len(messages_df)):
    removal=re.sub('[^a-zA-Z]',' ',messages_df['messages'][i])
    removal=removal.lower()
    removal=nltk.word_tokenize(removal)
    removal=[lemmatizerr.lemmatize(word)for word in removal if not word in set(stopwords.words('english'))]
    removal=' '.join(removal)
    corpus_3.append(removal)

In [55]:
corpus_2

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gon na home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breathe

In [94]:
corpus_3

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gon na home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw

In [61]:
from sklearn.feature_extraction.text import CountVectorizer
c_v=CountVectorizer(max_features=1500)
X=c_v.fit_transform(corpus_2).toarray()

In [95]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf=TfidfVectorizer(max_features=1500)
tfidf_vector=tf_idf.fit_transform(corpus_3).toarray()

In [62]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [96]:
tfidf_vector

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [64]:
from sklearn.preprocessing import LabelEncoder
label_enco=LabelEncoder()
encoding=label_enco.fit_transform(messages_df['labels'])

In [65]:
encoding

array([0, 0, 1, ..., 0, 0, 0])

In [67]:
y=pd.DataFrame(encoding,columns=['Labels'])

In [71]:
y.value_counts('Labels')

Labels
0    4825
1     747
dtype: int64

In [97]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(tfidf_vector,y,test_size=0.2)

In [78]:
len(y_test)

1115

In [82]:
import warnings
warnings.filterwarnings('ignore')

In [98]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB().fit(x_train,y_train)
y_preds=classifier.predict(x_test)

In [99]:
y_preds[0:6]

array([0, 0, 0, 0, 0, 0])

In [100]:
y_test[0:6]

Labels
4949       1
5118       0
198        0
1611       0
3878       0
5406       0

In [101]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion=confusion_matrix(y_test,y_preds)

In [90]:
# Using Bag of Words
confusion

array([[958,  12],
       [  5, 140]], dtype=int64)

In [102]:
# Using TF-IDF
confusion

array([[971,   0],
       [ 21, 123]], dtype=int64)

#### Word 2 Vec

In [141]:
from gensim.models import Word2Vec

In [235]:
paragraph_repeat = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [236]:
# Cleaning and pre-processing
text_cleaning=re.sub(r'\[[0-9]]*\]',' ',paragraph_repeat)
text_cleaning=re.sub(r'\s+',' ',text_cleaning)
text_cleaning=text_cleaning.lower()
text_cleaning=re.sub(r'\d',' ',text_cleaning)

In [237]:
text_cleaning

'i have three visions for india. in      years of our history, people from all over the world have come and invaded us, captured our lands, conquered our minds. from alexander onwards, the greeks, the turks, the moguls, the portuguese, the british, the french, the dutch, all of them came and looted us, took over what was ours. yet we have not done this to any other nation. we have not conquered anyone. we have not grabbed their land, their culture, their history and tried to enforce our way of life on them. why? because we respect the freedom of others.that is why my first vision is that of freedom. i believe that india got its first vision of this in     , when we started the war of independence. it is this freedom that we must protect and nurture and build on. if we are not free, no one will respect us. my second vision for india’s development. for fifty years we have been a developing nation. it is time we see ourselves as a developed nation. we are among the top   nations of the wo

In [238]:
sentences=nltk.sent_tokenize(text_cleaning)

In [239]:
sentences

['i have three visions for india.',
 'in      years of our history, people from all over the world have come and invaded us, captured our lands, conquered our minds.',
 'from alexander onwards, the greeks, the turks, the moguls, the portuguese, the british, the french, the dutch, all of them came and looted us, took over what was ours.',
 'yet we have not done this to any other nation.',
 'we have not conquered anyone.',
 'we have not grabbed their land, their culture, their history and tried to enforce our way of life on them.',
 'why?',
 'because we respect the freedom of others.that is why my first vision is that of freedom.',
 'i believe that india got its first vision of this in     , when we started the war of independence.',
 'it is this freedom that we must protect and nurture and build on.',
 'if we are not free, no one will respect us.',
 'my second vision for india’s development.',
 'for fifty years we have been a developing nation.',
 'it is time we see ourselves as a devel

In [240]:
tokenized_words=[nltk.word_tokenize(sentence) for sentence in sentences]

In [241]:
tokenized_words

[['i', 'have', 'three', 'visions', 'for', 'india', '.'],
 ['in',
  'years',
  'of',
  'our',
  'history',
  ',',
  'people',
  'from',
  'all',
  'over',
  'the',
  'world',
  'have',
  'come',
  'and',
  'invaded',
  'us',
  ',',
  'captured',
  'our',
  'lands',
  ',',
  'conquered',
  'our',
  'minds',
  '.'],
 ['from',
  'alexander',
  'onwards',
  ',',
  'the',
  'greeks',
  ',',
  'the',
  'turks',
  ',',
  'the',
  'moguls',
  ',',
  'the',
  'portuguese',
  ',',
  'the',
  'british',
  ',',
  'the',
  'french',
  ',',
  'the',
  'dutch',
  ',',
  'all',
  'of',
  'them',
  'came',
  'and',
  'looted',
  'us',
  ',',
  'took',
  'over',
  'what',
  'was',
  'ours',
  '.'],
 ['yet',
  'we',
  'have',
  'not',
  'done',
  'this',
  'to',
  'any',
  'other',
  'nation',
  '.'],
 ['we', 'have', 'not', 'conquered', 'anyone', '.'],
 ['we',
  'have',
  'not',
  'grabbed',
  'their',
  'land',
  ',',
  'their',
  'culture',
  ',',
  'their',
  'history',
  'and',
  'tried',
  'to',
  'e

In [242]:
exclud_stopwords=[]

In [233]:
# Loop for making list of words
for words in (tokenized_words):
    for word in  words:
        if word not in stopwords.words('english'):
            exclud_stopwords.append(word)  

In [243]:
for i in range (len(tokenized_words)):
    tokenized_words[i]=[word for word in tokenized_words[i] if word not in stopwords.words('english')]

In [244]:
tokenized_words

[['three', 'visions', 'india', '.'],
 ['years',
  'history',
  ',',
  'people',
  'world',
  'come',
  'invaded',
  'us',
  ',',
  'captured',
  'lands',
  ',',
  'conquered',
  'minds',
  '.'],
 ['alexander',
  'onwards',
  ',',
  'greeks',
  ',',
  'turks',
  ',',
  'moguls',
  ',',
  'portuguese',
  ',',
  'british',
  ',',
  'french',
  ',',
  'dutch',
  ',',
  'came',
  'looted',
  'us',
  ',',
  'took',
  '.'],
 ['yet', 'done', 'nation', '.'],
 ['conquered', 'anyone', '.'],
 ['grabbed',
  'land',
  ',',
  'culture',
  ',',
  'history',
  'tried',
  'enforce',
  'way',
  'life',
  '.'],
 ['?'],
 ['respect', 'freedom', 'others.that', 'first', 'vision', 'freedom', '.'],
 ['believe',
  'india',
  'got',
  'first',
  'vision',
  ',',
  'started',
  'war',
  'independence',
  '.'],
 ['freedom', 'must', 'protect', 'nurture', 'build', '.'],
 ['free', ',', 'one', 'respect', 'us', '.'],
 ['second', 'vision', 'india', '’', 'development', '.'],
 ['fifty', 'years', 'developing', 'nation', '.'

In [245]:
gensim_words=Word2Vec(tokenized_words,min_count=1)

In [246]:
vocab=gensim_words.wv['war']

In [247]:
vocab

array([-0.00219905, -0.00970885,  0.00929075,  0.00203636, -0.00116388,
       -0.00551955, -0.0085126 , -0.00989383,  0.00894091, -0.00250522,
        0.00459427, -0.00452481,  0.00995189,  0.00366171,  0.00103129,
       -0.00403834,  0.00122027, -0.00265451,  0.00735284,  0.00447542,
        0.00099955,  0.0034782 ,  0.00372712, -0.00680036,  0.00893242,
        0.00173499, -0.00579935,  0.00866838, -0.00129286,  0.00818304,
       -0.0014927 ,  0.00698649,  0.00273452, -0.00436226, -0.00374683,
        0.00919046,  0.00159645, -0.00599784,  0.00034776, -0.00195135,
        0.00159242, -0.00771525,  0.00738298,  0.00131083,  0.00787099,
        0.00445568, -0.00439675,  0.00376054, -0.0006357 , -0.00984484,
        0.00825004,  0.00964326,  0.00965426, -0.00379659, -0.00844202,
        0.00483581, -0.00765107,  0.00853567,  0.00275977,  0.00560496,
        0.00611362,  0.00046455, -0.00209463,  0.000778  ,  0.00983559,
       -0.00711718, -0.00155744, -0.00235984,  0.00487084,  0.00

In [249]:
vocab=gensim_words.wv.most_similar('india')

In [250]:
vocab

[('military', 0.370004802942276),
 ('took', 0.21221157908439636),
 ('greeks', 0.20217649638652802),
 ('three', 0.19961437582969666),
 ('prakash', 0.1892213374376297),
 ('developing', 0.18216250836849213),
 ('see', 0.17356351017951965),
 ('protect', 0.17105315625667572),
 ('must', 0.17062465846538544),
 ('recognised', 0.16197067499160767)]