In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow import keras

In [2]:
sentences=['I dont like this job',
          'Please Allah help me in finding new job',
          'I love Machine Learning',
          'I support Liverpool',
          'Ronaldo and Messi can not be compared']

In [3]:
sentences

['I dont like this job',
 'Please Allah help me in finding new job',
 'I love Machine Learning',
 'I support Liverpool',
 'Ronaldo and Messi can not be compared']

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
vac_size=10000

In [10]:
one_hot_representation=[]
for words in sentences:
    one_hot_r=one_hot(words,vac_size)
    one_hot_representation.append(one_hot_r)

In [11]:
print(one_hot_representation)

[[6465, 6856, 5511, 6920, 9814], [4828, 3862, 6316, 4191, 8854, 7463, 9396, 9814], [6465, 5087, 4123, 7811], [6465, 2806, 2170], [5100, 9580, 7552, 5475, 1567, 659, 535]]


### WORD EMBEDDING REPRESENTATION

### Padding

In [14]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [17]:
sentence_length=11
padded_data=pad_sequences(one_hot_representation,maxlen=sentence_length,padding='pre')

In [18]:
print(padded_data)

[[   0    0    0    0    0    0 6465 6856 5511 6920 9814]
 [   0    0    0 4828 3862 6316 4191 8854 7463 9396 9814]
 [   0    0    0    0    0    0    0 6465 5087 4123 7811]
 [   0    0    0    0    0    0    0    0 6465 2806 2170]
 [   0    0    0    0 5100 9580 7552 5475 1567  659  535]]


In [20]:
dim=12

In [21]:
model=Sequential()
model.add(Embedding(vac_size,dim,input_length=sentence_length))
model.compile('adam','mse')

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 11, 12)            120000    
                                                                 
Total params: 120,000
Trainable params: 120,000
Non-trainable params: 0
_________________________________________________________________


In [24]:
print(model.predict(padded_data))

[[[-0.04296672  0.02921304  0.03514918  0.02721332  0.01498261
   -0.04108546 -0.04224465  0.01690901 -0.02630378 -0.03509025
    0.03303719  0.00751147]
  [-0.04296672  0.02921304  0.03514918  0.02721332  0.01498261
   -0.04108546 -0.04224465  0.01690901 -0.02630378 -0.03509025
    0.03303719  0.00751147]
  [-0.04296672  0.02921304  0.03514918  0.02721332  0.01498261
   -0.04108546 -0.04224465  0.01690901 -0.02630378 -0.03509025
    0.03303719  0.00751147]
  [-0.04296672  0.02921304  0.03514918  0.02721332  0.01498261
   -0.04108546 -0.04224465  0.01690901 -0.02630378 -0.03509025
    0.03303719  0.00751147]
  [-0.04296672  0.02921304  0.03514918  0.02721332  0.01498261
   -0.04108546 -0.04224465  0.01690901 -0.02630378 -0.03509025
    0.03303719  0.00751147]
  [-0.04296672  0.02921304  0.03514918  0.02721332  0.01498261
   -0.04108546 -0.04224465  0.01690901 -0.02630378 -0.03509025
    0.03303719  0.00751147]
  [ 0.01627247 -0.00696682  0.02521088  0.01730522 -0.02270776
    0.0223146

In [25]:
print(model.predict(padded_data[0]))

[[-0.04296672  0.02921304  0.03514918  0.02721332  0.01498261 -0.04108546
  -0.04224465  0.01690901 -0.02630378 -0.03509025  0.03303719  0.00751147]
 [-0.04296672  0.02921304  0.03514918  0.02721332  0.01498261 -0.04108546
  -0.04224465  0.01690901 -0.02630378 -0.03509025  0.03303719  0.00751147]
 [-0.04296672  0.02921304  0.03514918  0.02721332  0.01498261 -0.04108546
  -0.04224465  0.01690901 -0.02630378 -0.03509025  0.03303719  0.00751147]
 [-0.04296672  0.02921304  0.03514918  0.02721332  0.01498261 -0.04108546
  -0.04224465  0.01690901 -0.02630378 -0.03509025  0.03303719  0.00751147]
 [-0.04296672  0.02921304  0.03514918  0.02721332  0.01498261 -0.04108546
  -0.04224465  0.01690901 -0.02630378 -0.03509025  0.03303719  0.00751147]
 [-0.04296672  0.02921304  0.03514918  0.02721332  0.01498261 -0.04108546
  -0.04224465  0.01690901 -0.02630378 -0.03509025  0.03303719  0.00751147]
 [ 0.01627247 -0.00696682  0.02521088  0.01730522 -0.02270776  0.02231462
   0.01652176 -0.0088249  -0.042